### ISSUE TITLE
스케치북5 대응 플러그인 갤러리,웹진형 페이지 이동시 오류

### ISSUE THREAD

**Issue by wookho** [izuzero/xe-module-ajaxboard-plugins#3]
이전에 API용 대응스킨에서 발생했던 동일한 현상입니다. 
페이지 이동시 목록이 사라져 게시글 열람이 불가능해 집니다.

**Comment by izuzero** [comment]
잘 작동한다면 댓글 하나 남겨주세요 :)

**Comment by izuzero** [comment]
릴리즈 준비로 이슈 닫겠습니다.

**Comment by wookho** [comment]
@izuzero 네. 한가지 확인할 것이 있어 댓글이 늦었네요. 이상없이 잘 됩니다. 감사합니다.

**Comment by wookho** [comment]
https://github.com/izuzero/xe-module-ajaxboard-plugins/issues/3

이 수정사항 적용해 보려고 다운받아 테스트해보니 페이지이동과 추천시 새로고침이 발생되는 것이 확인되어 사이트에는 다시 1.0.1로 설치하였습니다.

**Comment by wookho** [comment]
@izuzero 다운받은 경로는 https://github.com/izuzero/xe-module-ajaxboard-plugins/tree/sketchbook5 입니다. (#3 테스트해 보려고 다운 받았던 경로....)

**Comment by izuzero** [comment]
@wookho 다시 받아서 플러그인을 테스트 페이지에 활성화시켜놓고 링크 주세요. 문제 확인해보겠습니다.

**Comment by wookho** [comment]
@izuzero 네. 방금 다시 최신버전으로 업데이트해 놓았습니다. http://pomelove.com/xe/my_pom

게시판은 아무 게시판이나 페이지 이동을 해 보시면 알 수 있을거에요.

**Comment by izuzero** [comment]
https://github.com/izuzero/xe-module-ajaxboard-plugins/tree/sketchbook5-develop
이 브랜치로 테스트해주세요.

**Comment by wookho** [comment]
@izuzero 방금 말씀하신 경로 다운받아 업데이트 했습니다. 증상은 동일한 거 같아요.

**Comment by izuzero** [comment]
뭐가 문제인지 알 수가 없어요 @_@;
[이 줄](https://github.com/izuzero/xe-module-ajaxboard-plugins/blob/sketchbook5-develop/sketchbook5/js/plugin.js#L69) 위에 console.log("TEST"); 라고 하나 적어 넣어주실 수 있을까요?

**Comment by wookho** [comment]
@izuzero 말씀하신 곳에 console.log("TEST");  입력해 놓았습니다.

**Comment by izuzero** [comment]
아약스보드 모듈을 develop 브랜치에 있는 걸로 덮어써주세요.

**Comment by wookho** [comment]
@izuzero 모듈 업데이트했습니다.

**Comment by izuzero** [comment]
잘 되네요. 호환성 유지를 위해 커밋 하나 하고 이슈 닫겠습니다.
