### ISSUE TITLE
댓글, 글 등의 총체적 오류

### ISSUE THREAD

**Issue by ioz2014** [izuzero/xe-module-ajaxboard-plugins#4]
http://php.raonnet.com/index.php?mid=test

테스트 주소입니다.
플러그인 적용하였고 모듈은 develop 최신 버전입니다. 전체적으로 작동하지 않습니다.

하나 더, 플러그인을 plugin 디렉토리에 업로드했는데도 모듈의 플러그인 목록에는 즉각 안뜹니다. 플러그인 목록에서 저장버튼 한번 눌러주고 캐시파일 재생성하니까 그제서야 뜨더라고요.

**Comment by izuzero** [comment]
https://github.com/izuzero/xe-module-ajaxboard-plugins/tree/sketchbook5
해당 브랜치로 다시 한 번 테스트해주세요.
플러그인 목록이 바로 반영되지 않는 이유는 캐시가 적용되어 있어서 그런 것뿐입니다. 정상입니다.

**Comment by ioz2014** [comment]
이미 통신 메시지 삭제 전의 버전으로 깔아서 해봤지만 똑같았고, 지금 다시 깔아서 해봤지만 역시 똑같습니다.

댓글 작성시 갱신조차 되지 않습니다.

**Comment by izuzero** [comment]
default 플러그인이랑 sketchbook5 플러그인이랑 동시에 켜져 있네요... 이러면 안 됩니다.

**Comment by ioz2014** [comment]
아... 죄송합니다. default를 끄니 정상 동작하네요.. 괜히 번거롭게 해드려서 죄송합니다.

단 글 삭제는 페이지 이동을 하는 것 같습니다.

**Comment by izuzero** [comment]
@ioz2014 스케치북에는 글 삭제 기능이 추가되어 있지 않습니다 :)

**Comment by ioz2014** [comment]
순식간에 명쾌하게 모든게 정리됐네요ㅋㅋ 답변해주셔서 감사합니다.
