### ISSUE TITLE
스케치북 모바일도 이 플러그인으로 해결되는건가요?

### ISSUE THREAD

**Issue by ioz2014** [izuzero/xe-module-ajaxboard-plugins#5]
모바일에도 사용 체크해주면 모바일에서도 작동이 되는 것인지 궁금합니다.

그리고 스케치북도 그냥 기본 플러그인에 추가하셔서 같이 관리하시는게 어떨지 제안을 드립니다. 무료 스킨인데다 어찌보면 default보다도 잦게 사용되는 스킨인데 이렇게 분리해놓으시면 관리와 업데이트에 들이는 시간만 두 배로 드시지 않을까요?

추신: 연초부터 이렇게 신속하게 버그 해결해나가시는 모습, 개선하시는 모습이 참 존경스럽습니다. 나중에 실사용하면서 감사함 잊지 않겠습니다.

**Comment by izuzero** [comment]
모듈에 들어가는 기본 플러그인은 정말 말 그대로 기본 플러그인만 넣은 거에요.
새로운 플러그인 만들 때마다 모듈에 기본으로 들여보내면 이게 더 관리가 힘들단 말이죠 ㅎㅎ..

**Comment by izuzero** [comment]
스케치북 모바일에서도 플러그인 작동합니다.

**Comment by ioz2014** [comment]
그렇겠군요. 제가 생각이 짧았네요.
